# Generated by Django 4.2.1 on 2023-06-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
